export const playlists = [
  {
    id: "4janzDyPODSCKDCXdWLbJy",
    name: "Halloween 2022",
    inClassicMode: true,
    style: "Musiques terrifiantes",
  },
  {
    id: "0cY1qx19t14YlfMkbW0HIw",
    name: "Blindtest Playlist . 1960-2022 (1000+ songs)",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Tout genre 1960-2022",
  },
  {
    id: "37i9dQZF1DWXRqgorJj26U",
    name: "Classic rock",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Classic rock",
  },
  {
    id: "4l1CEhc7ZPbaEtiPdCSGbl",
    name: "rap fr 2022",
    inClassicMode: false,
    style: "Rap FR 2022",
  },
  {
    id: "6Jf4xwIOffHI00KYmV0cmk",
    name: "bad playlist (tommy)",
    inClassicMode: false,
    style: "Playlist de Tommy",
  },
  {
    id: "37i9dQZF1DXdfOcg1fm0VG",
    name: "Video game soundtrack",
    inClassicMode: false,
    style: "Video game soundtrack",
  },
  {
    id: "37i9dQZF1DX1tz6EDao8it",
    name: "Movie soundtrack",
    inClassicMode: false,
    style: "Movie soundtrack",
  },
  {
    id: "37i9dQZF1DXacPj7eARo6k",
    name: "Années 2000",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Années 2000",
  },
  {
    id: "37i9dQZF1DWWl7MndYYxge",
    name: "Années 80",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Années 80",
  },
  {
    id: "2IamgqJjhiz48fBY9W0kpa",
    name: "Blind test - 80s / 90s / 00s / 10s / 20s",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Tout genre 1980-2020",
  },
  {
    id: "1tLCfsiP8mv5dIsC7YfPyc",
    name: "Ultime Blind Test (80-2021)",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Tout genre 1980-2021",
  },
  {
    id: "37i9dQZEVXbIPWwFssbupI",
    name: "Top 50 - France",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Top 50 - France",
  },
  {
    id: "37i9dQZEVXbMDoHDwVN2tF",
    name: "Top 50 - Global",
    // inClassicMode: true,
    inClassicMode: false,
    style: "Top 50 - Global",
  },
];
