name: Hourly cron job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request GET \
          --url 'https://ads-music-quizz.vercel.app/api/track'
